services:
  - type: web
    name: zoro-autorename-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: USE_WEBHOOK
        value: "true"
      - key: PORT
        value: "10000"
